#!/bin/sh -xv

#
# $Id: run 238 2007-10-04 19:10:45Z YetkinYilmaz $
#
# Execute a CMSSW job submitted through Condor
#

#
# Prologue
#
 
echo ; date ; echo
echo ; hostname ; echo
echo ; echo "--- disk space ---" ; echo ; df . ; echo ; echo "--- ---------- ---" ; echo
echo ; echo "--- limits ---" ; echo ; ulimit -a ; echo ; echo "--- ------ ---" ; echo
echo "Cwd: `pwd`"
echo ; echo "--- Env ---" ; env ; echo "--- --- ---" ; echo

#
# Episode 1
#

prog=`basename $0`
config=$1


usage()
{
   cat <<EOF >&2

Usage: $prog file.cfg

EOF

   exit 1
}

[ $# -ne 1 ] && usage;

config=$1


#
# Load config
#

if [ ! -r "$1" ]; then
   echo "$prog: configfile ' $1' not readable" >&2
   exit 1
fi

echo
echo "--- Config Vars ---"
sed -e '1,/^#CFGSTART/d' -e '/^#CFGEND/,$d' -e 's/^#[ 	]*//' -e '/^[ 	]*$/d' < $config
sed -e '1,/^#VARSTART/d' -e '/^#VAREND/,$d' -e 's/^#[ 	]*//' -e '/^[ 	]*$/d' < $config
echo "--- ----------- ---"
echo
eval `sed -e '1,/^#CFGSTART/d' -e '/^#CFGEND/,$d' -e 's/^#[ 	]*//' -e '/^[ 	]*$/d' < $config`
eval `sed -e '1,/^#VARSTART/d' -e '/^#VAREND/,$d' -e 's/^#[ 	]*//' -e '/^[ 	]*$/d' < $config`

#
# Prepare input
#

if [ -n "$JOB_RUN_HIROOT" ]; then

   # run HIROOT ..
   true

elif [ -n "$JOB_INPUT" ]; then

   input=${BASE}.hepmc
   input_src=${JOB_INPUT}/${input}
   if [ -f ${input_src}.bz2 ]; then
      bzcat ${input_src}.bz2 > $input
   elif [ -f ${input_src}.gz ]; then
      zcat ${input_src}.gz > ${input}
   elif [ -f ${input_src} ]; then
      cp ${input_src} ${input}
   else
      echo "$prog: inputfile not found ($input_src)." >&2
      exit 1
   fi

fi


#
# Initialize SCRAM environment
#

if [ -z "$SCRAM_DIR" ]; then
   echo "$prog: SCRAM_DIR configuration variable missing." >&2
   exit 1
fi

if [ ! -d "$SCRAM_DIR" ]; then
   echo "$prog: SCRAM_DIR ($SCRAM_DIR) : file not readable." >&2
   exit 1
fi

## default is now sl4
#if test -z "$SCRAM_ARCH"; then
#   export SCRAM_ARCH=slc4_ia32_gcc345
#fi
#
#if test "$SCRAM_ARCH" = "slc3_ia32_gcc323"; then
#   source /app/cms/cmsset_default.sh
#else
#   source /app/cms-soft/cmsset_default.sh
#fi

cd $SCRAM_DIR
export SCRAM_ARCH=slc4_ia32_gcc345
source /app/cms-soft/cmsset_default.sh
eval `scramv1 runtime -sh`
cd -

#
# Run job
#

time cmsRun $config < /dev/null > cmsRun.out 2> cmsRun.err


#
# Store output
#

output=$BASE.root
output_src=`pwd`/$output
if test -e $output; then
    edmEventSize $output
	check_file=$?
	if [ $check_file = "0" ]; then
#	    cmsRun test.cfg > filetest
#            filestatus="`cat filetest | grep 'FILE STATUS'`"
#            if [ "$filestatus" = "FILE STATUS : GOOD" ]; then
		if [ -n "$JOB_OUTPUT" -a -s "$output_src" ]; then
		    output_dest=$JOB_OUTPUT/$output
		    case $output_dest in
			/pnfs/*)
			    /opt/dcap/bin/dccp $input ///pnfs/cmsaf.mit.edu/hibat/cms/mc/$BASE/hepmc/
			    touch ${output}.good
			    echo /opt/dcap/bin/dccp $output_src $output_dest
			    /opt/dcap/bin/dccp $output_src $output_dest;;
			*)
			    echo cp $output_src $output_dst
			    cp $output_src $output_dst;;
		    esac
		    echo "File copied to Output Directory : $output" >&2
		fi   
#	    else
#		echo "Bad File : $output" >&2
#		mv $output ${output}.bad
#	    fi
	else
	    echo "Bad File : $output" >&2
	    mv $output ${output}.bad
	fi
else
    echo "Failed to produce $BASE.root" >&2
    touch ${output}.none
fi
#
# TODO: remove output file on successful storage
#


#
# epilogue
#

#rm *.root

# remove the hepmc input file to avoid unneeded file transfer
# [ -n "$input" ] && rm -f $input

# compress the log file
bzip2 cmsRun.out
bzip2 cmsRun.err

ls -lha

