#!/bin/sh

cfg=$1

datatag=pythia_dijet_pt100to9999_d20081021
mixtag=nomix

a=$PWD

cd ~edwenger/cmssw/src
. ~edwenger/set

cd $a

run=`printf "%06d" $2`
event=$3
let "skipevent = $event - 1" 

mkdir proc-$run-$event
cd proc-$run-$event

random=$RANDOM
cat $a/$cfg | replace __DATATAG__ $datatag | replace __MIXTAG__ $mixtag | replace __OUTPUT__ mix_and_digi_r${run}_e${event} | replace __RUN__ ${run} | replace __SKIPEVENT__ ${skipevent} | replace __RANDOM__ ${random}> run${run}_event${event}_cfg.py
cmsRun run${run}_event${event}_cfg.py 1>${run}.run.${event}.event.out 2>${run}.run.${event}.event.err

dccp mix_and_digi_r${run}_e${event}.root ~edwenger/dcache/mix_and_digi/$mixtag/${datatag}_r${run}_e${event}.root
rm mix_and_digi_r${run}_e${event}.root

cd ..
tar cvfz $cfg-$datatag-r$run-e$event.tgz proc-$run-$event
rm proc-$run-$event -rf