#!/bin/sh

cfg=$1

datatag=pythia_dijet_pt100to9999_d20081021
mixtag=nomix

a=$PWD

cd ~edwenger/cmssw/src
. ~edwenger/set

cd $a

run=`printf "%06d" $2`
event=$3

mkdir proc-$run-$event
cd proc-$run-$event

cat $a/$cfg | replace __MIXTAG__ $mixtag | replace __INPUT__ ${datatag}_r${run}_e${event} | replace __OUTPUT__ trk_and_ana_r${run}_e${event} > run${run}_event${event}_cfg.py
cmsRun run${run}_event${event}_cfg.py 1>${run}.run.${event}.event.out 2>${run}.run.${event}.event.err

dccp trk_and_ana_r${run}_e${event}.root ~edwenger/dcache/trk_and_ana/$mixtag/${datatag}_r${run}_e${event}.root
rm trk_and_ana_r${run}_e${event}.root

cd ..
tar cvfz $cfg-$datatag-r$run-e$event.tgz proc-$run-$event
rm proc-$run-$event -rf
